name: "CI"
on:
  push:
    branches:
      - master
    tags:
      - v*
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Run tests (non-Linux environment)
        run: npm test
        if: runner.os != 'Linux'
      - name: Run tests (Linux environment)
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - name: Publish
        if: success() && startsWith( github.ref, 'refs/tags/v') && matrix.os == 'ubuntu-latest'
        run: |
          npm install -g vsce
          vsce publish -p ${{ secrets.VSCE_PAT }}
